services:
  - type: web
    name: claritas-verify-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SENDER_NAME
        value: Claritas Verify
      - key: FRONTEND_URL
        value: https://claritasverify.netlify.app
      - key: DEV_EMAIL_BACKUP
        value: false